### ISSUE TITLE
Improvement - Contribution (Landing Page)

### ISSUE THREAD

**Issue by niklasros** [scania-digital-design-system/sdds-website#182]
**Describe current situation**  
_The text in the Contribute box on the landing page has moved to the wrong position._

**Describe the improvement**  
_Re-align the text._

**Screenshots**  
_Implementation_
![contribute-implementation](https://user-images.githubusercontent.com/59045455/102461840-476c4400-4049-11eb-99ab-faa721478997.png)

_Design in Figma_
<img width="1680" alt="contribute-figma" src="https://user-images.githubusercontent.com/59045455/102461864-5521c980-4049-11eb-87fe-0ff3ede5deab.png">

**Additional context**  
https://digitaldesign.netlify.app/home

**Comment by mmexvr** [comment]
Talk with @niklasros regarding fluid and normal grid usage

This issue is related with how the fluid grid works. We have a container fluid on the banner which makes it follow the columns width that increases if the screen get bigger. 
- We can follow the grid and just remove the fluid part of the banner  
- We can mix the fluid grid and regular grid at the same time, but then we need to add some kind of design in figma to make sure it follows it

This is general for the whole site, should we mix fluid container and regular containers

**Comment by mmexvr** [comment]
Remove fluid and align the button
